const data = [
  {
    fName: 'John',
    lName: 'Doe',
    dateOfBirth: '1990-01-01',
    countOfOwnedCars: 2,
  },
  {
    fName: 'Jane',
    lName: 'Doe',
    dateOfBirth: '1985-02-15',
    countOfOwnedCars: 1,
  },
  {
    fName: 'Michael',
    lName: 'Smith',
    dateOfBirth: '1979-05-20',
    countOfOwnedCars: 3,
  },
  {
    fName: 'Emily',
    lName: 'Johnson',
    dateOfBirth: '1992-08-30',
    countOfOwnedCars: 1,
  },
  {
    fName: 'James',
    lName: 'Brown',
    dateOfBirth: '1980-03-12',
    countOfOwnedCars: 2,
  },
  {
    fName: 'Linda',
    lName: 'Williams',
    dateOfBirth: '1995-06-10',
    countOfOwnedCars: 1,
  },
  {
    fName: 'Robert',
    lName: 'Jones',
    dateOfBirth: '1978-11-04',
    countOfOwnedCars: 4,
  },
  {
    fName: 'Patricia',
    lName: 'Miller',
    dateOfBirth: '1987-09-17',
    countOfOwnedCars: 2,
  },
  {
    fName: 'William',
    lName: 'Davis',
    dateOfBirth: '1993-01-22',
    countOfOwnedCars: 3,
  },
  {
    fName: 'Elizabeth',
    lName: 'Garcia',
    dateOfBirth: '1990-07-14',
    countOfOwnedCars: 1,
  },
  {
    fName: 'David',
    lName: 'Martinez',
    dateOfBirth: '1988-10-05',
    countOfOwnedCars: 2,
  },
  {
    fName: 'Susan',
    lName: 'Hernandez',
    dateOfBirth: '1994-04-20',
    countOfOwnedCars: 3,
  },
  {
    fName: 'Joseph',
    lName: 'Lopez',
    dateOfBirth: '1982-12-18',
    countOfOwnedCars: 1,
  },
  {
    fName: 'Sarah',
    lName: 'Gonzalez',
    dateOfBirth: '1986-02-25',
    countOfOwnedCars: 2,
  },
  {
    fName: 'Charles',
    lName: 'Wilson',
    dateOfBirth: '1977-03-02',
    countOfOwnedCars: 3,
  },
  {
    fName: 'Jessica',
    lName: 'Anderson',
    dateOfBirth: '1991-05-19',
    countOfOwnedCars: 1,
  },
  {
    fName: 'Daniel',
    lName: 'Thomas',
    dateOfBirth: '1983-06-29',
    countOfOwnedCars: 4,
  },
  {
    fName: 'Dorothy',
    lName: 'Taylor',
    dateOfBirth: '1989-08-12',
    countOfOwnedCars: 2,
  },
  {
    fName: 'Thomas',
    lName: 'Moore',
    dateOfBirth: '1996-02-17',
    countOfOwnedCars: 3,
  },
];
